$(document).ready(function(){
				
					$("#choix1").click(function(){
						a=0;
						b=3;
						if(a==b){
							console.log("prout");
						}else{
							console.log("pwet");
						}
					});
					$("#choix2").click(function(){
						a=1;
						b=3;
						if(a==b){
							console.log("prout");
						}else{
							console.log("pwet");
						}
					});
					$("#choix3").click(function(){
						a=2;
						b=3;
						if(a==b){
							console.log("prout");
						}else{
							console.log("pwet");
						}
					});
					$("#choix4").click(function(){
						a=3;
						b=3;
						if(a==b){
							console.log("prout");
						}else{
							console.log("pwet");
						}
					});
				});